### ISSUE TITLE
Insert using Dictionary instead of Class

### ISSUE THREAD

**Issue by zsoflin** [mrsharpoblunto/BobbyTables#5]
Hi!
First of all, thank you for your library. I am writing a plugin that uses your library in a visual scripting program called Grasshopper  and was curious if it was possible to insert records into tables via a Dictionary Object rather than using a class. The reason is, I would like users to be able to define the keys/values, their number, and type. Is this possible with this library? 

Thank you in advance!
-Zach

Example:

```
var rec = new Dictionary<String, Object> ();

rec["date"] = DateTime.Now();
rec["items"] = "eggs";

var table = datastore.GetTable<Dictionary<String, Object>>("groceries");
table.Insert(rec);
```

**Comment by mrsharpoblunto** [comment]
Hi there,

That use case wasn't really supported, but now I have added support in the new 1.3.4 release for storing objects that implement the IDictionary&lt;string,object&gt; interface. This also allows you to use the .NET 4+ dynamic expando object (which implements this interface) which depending on your needs might be a bit tidier looking than storing Dictionaries directly.

```
dynamic record = new ExpandoObject();
record.date = DateTime.Now();
record.items = "eggs";

var table = datastore.GetTable<ExpandoObject>("groceries");
table.Insert(record);
```

**Comment by zsoflin** [comment]
Wow, thank you so much. This works great!
-Zach
