### ISSUE TITLE
400 Bad Request Errors

### ISSUE THREAD

**Issue by blanning** [mrsharpoblunto/BobbyTables#6]
When I use any flavor of the GetOrCreate method (synchronous or asynchronous) for a table name that does yet exist in the data store I get back a 400 error.

The same call to a table that already exists in the datastore works fine.

v. 1.0.0.0

**Comment by mrsharpoblunto** [comment]
So you can't create new tables? I haven't seen an issue with that in the past, but I'll have a look anyway - perhaps you could show a minimal snippet of the code you're using that reproduces the error. Also I'm guessing you're not using v1.0.0.0 as the earliest release available on nuget is 1.0.3. If you are using an older version, try upgrading and see if the problem goes away.

**Comment by blanning** [comment]
Code Snippit

```
public static async void CreateDataStore()
    {
        var manager = new DatastoreManager(<KeyIncludedHere>);
        try
        {
            // This is the problem line, if this datastore name does not already exist the call fails with GetOrCreate.
            var datastore = await manager.GetOrCreateAsync("test");

            await datastore.PullAsync();

            var table = datastore.GetTable<Settings>("settings");

            var setts = new Settings
            {
            //Create new settings object to pass in
            };

            table.Insert(setts);

            if (await datastore.PushAsync())
            {
                MessageBox.Show("It Worked");
            }
            else
            {
                MessageBox.Show("Something went wrong");
                datastore.Revert();
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.ToString());
        }
    }
```

https://www.dropbox.com/s/74l9jved4z8dr9d/BobbyTablesAssemblyReference.png?dl=0

And here is an image of the assembly that NuGet thinks is the newest, where should I be checking for the accurate version number if this is not it?

If I use a simple create command (not getorcreate) then the create works and once the datastore exists I can use getorcreate to access it.

**Comment by blanning** [comment]
And thanks for the response and help BTW.

**Comment by toffalori** [comment]
I have exactly the same issue in v1.3.5. .Net 4.5.
GetOrCreateAsync throws error 400 (BAD REQUEST) when the datastore does not already exist.

**Comment by blanning** [comment]
Yeah, after some digging the NuGet package tells NuGet that it is `bobbytables version 1.3.5`, but the assembly version shown as a .dll is still `1.0.0`, so it is just a matter of them being out of sync, not of an old package.

Also, I have tried several other programming setups as far as code layout and order of steps in totally new projects and still get the same thing.

**Comment by mrsharpoblunto** [comment]
I've had a look and it works fine for me, but I think I know where you might be going wrong. 

I am guessing that you are using your application key when initializing the DatastoreManager instead of using an oauth token. (As per the bobbytables docs), you need to get an oauth token from dropbox before you can make calls to the Datastore API. For info on how to get an oauth token from dropbox, look here https://www.dropbox.com/developers/core/docs#oa2-authorize. 

Once you've got your oauth token, use that in the DatastoreManager constructor instead of the App key.

**Comment by blanning** [comment]
Actually I am currently using the temporary bearer token that you can generate from the AppConsole page, which is how the Dropbox tutorial shows to access the Datastore API. (For testing purposes of course). But thanks, I will give it a try and see what I get.
